version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: php:7.1-apache
        environment:
          APP_ENV: test
    steps:
       - checkout
       - run:
          name: Install system packages
          command: apt-get update && apt-get -y install zip git zlib1g-dev wget
       - run:
          name: Install PHP extensions
          command: |
            docker-php-ext-install pdo
            docker-php-ext-install zip
       - run:
          name: Display PHP information
          command: |
            php -v
       - run:
          name: Check PHP sintax
          command: find . -name \*.php -exec php -l "{}" \;
       - persist_to_workspace:
          root: /
          paths:
            - app

  publish:
    working_directory: /
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /
      - run:
          name: Copy CI files to root
          command: |
             cd /app
             cp .circleci/data/Dockerfile .
             cp .circleci/data/wait-for-mysql.sh .
             cp .circleci/data/magento2_module_install.sql .
      - run:
          name: Build image base for modifications
          command: |
             cd /app
             ls
             docker build -t ${DOCKER_ACCOUNT}/${PROJECT_NAME}:latest .
             docker run --name newimage -d -p3306:3306 -p80:80 ${DOCKER_ACCOUNT}/${PROJECT_NAME}:latest
             docker exec -it newimage ls
             docker exec -it newimage sh -c "mkdir /app/tmp"
             docker cp /app/wait-for-mysql.sh newimage:app/tmp/
             docker cp /app/magento2_module_install.sql newimage:app/tmp/
      - run:
          name: Install and run Functional Tests dependencies
          command: |
            docker exec -i newimage sh -c \
              "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
              echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
              apt-get -y update && apt-get -y install google-chrome-unstable"
              
            docker exec --detach newimage google-chrome-unstable --disable-gpu --no-sandbox --headless --remote-debugging-address=127.0.0.1 --remote-debugging-port=9222 --disable-extensions   
            docker exec -it newimage sh -c "git clone https://github.com/mundipagg/ecommerce-test-package.git /behat-test"
      - run:
          name: Activate and setup Plugin
          command: |
            docker exec -it newimage sh -c "ls"
            docker exec -it newimage sh -c "ls /app"
            docker exec -it newimage sh -c "cd /var/www/html && rm composer.lock"
            docker exec -it newimage sh -c "cd /var/www/html && composer require mundipagg/mundipagg-magento2-module -vvv"
            docker exec -it newimage sh -c "cd /var/www/html && composer update -vvv"
            docker exec -it newimage sh -c "cd /var/www/ && find html/ -type d -exec chmod 775 {} \;"
            docker exec -it newimage sh -c "cd /var/www/ && find html/ -type f -exec chmod 664 {} \;"
            docker exec -it newimage sh -c "cd /var/www/ && chown -R www-data:www-data html/"
            docker exec -it newimage sh -c "cd /var/www/html && php bin/magento setup:upgrade"
            docker exec -it newimage sh -c "cd /var/www/html && php bin/magento setup:di:compile"
            docker exec -it newimage php index.php
            docker exec -it newimage mysql magento2 -e \
            "update core_config_data set value = '${STG_URL}' where path = 'web/unsecure/base_url';"
            docker exec -it newimage mysql magento2 -e \
                        "insert into core_config_data (scope, scope_id, path, value) \
                        values ('default', 0, 'web/secure/base_url', '${STG_URL}');"

            docker exec -it newimage mysql magento2 -e \
            "INSERT INTO magento2.core_config_data VALUES (null, 'default', 0, 'customer/address/taxvat_show', 1);"

            docker exec -it newimage mysql magento2 -e \
              "update magento2.core_config_data set value = '1' \
              where path like 'customer/create_account/vat_frontend_visibility';"

            docker exec -it newimage mysql magento2 -e \
              "INSERT INTO magento2.core_config_data (scope, scope_id, path, value) VALUES \
              ('default', 0, 'mundipagg_mundipagg/global/secret_key_test', '${API_TEST_SECRET_KEY}'), \
              ('default', 0, 'mundipagg_mundipagg/global/public_key_test', '${API_TEST_PUBLIC_KEY}');"

            docker exec -it newimage /bin/sh -c "mysql magento2 < /app/tmp/magento2_module_install.sql"

            docker exec -it newimage sh -c "cd /var/www/html && php bin/magento cache:flush"
            docker exec -it newimage sh -c "cd /var/www/html && php bin/magento setup:di:compile"
      - run:
          name: Clear useless files
          command: |
            pwd
      - deploy:
          name: Commit and push Docker image
          command: |
             sleep 5 && docker stop newimage
             docker login ${DOCKER_ACCOUNT} -u ${DOCKER_USER} -p ${DOCKER_PASS}
             docker commit newimage ${DOCKER_ACCOUNT}/${PROJECT_NAME}:latest
             docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:latest"
             docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_BRANCH}"
             docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_SHA1:0:8}"
             docker push "${DOCKER_ACCOUNT}/${PROJECT_NAME}"
  deploy_staging:
     machine: true
     steps:
       - run:
           name: Test Swagger
           command: | 
             response=$(curl -s -o /dev/null -I -w "%{http_code}" http://stg-magento2.mundipagg.com/rest/all/schema?services=all)
             if [ "$response" = '200' ]; then echo 'Swagger Ok'; else echo 'Swagger invalid'; exit 1; fi
       - run:
           name: Send deployment webhook to Rancher
           command: |
             BODY='{"push_data":{"tag":"'"${CIRCLE_BRANCH}"'"},"repository":{"repo_name":"'"${DOCKER_ACCOUNT}/${PROJECT_NAME}"'"}}'
             curl -X POST ${RANCHER_STG_DEPLOY_URL} -H 'Content-Type: application/json' -d "${BODY}"
workflows:
  version: 2
  build_publish_deploy:
    jobs:
      - build
      - publish:
          context: DockerRegistry
          requires:
            - build

      - deploy_staging:
          requires:
            - publish
